import '../models/message.dart';
import 'database_service.dart';

class MessageSeeder {
  static const List<String> motivationalMessages = [
    "You are capable of amazing things",
    "Every small step forward is progress",
    "Your potential is limitless",
    "You have overcome challenges before, you can do it again",
    "Today is a new opportunity to grow",
    "You are stronger than you think",
    "Your efforts matter and make a difference",
    "Believe in yourself, you've got this",
    "You are exactly where you need to be",
    "Your journey is unique and valuable",
    "You survived 100% of your worst days",
    "Your plants believe in you",
    "Someone's day is better because you exist",
    "You're doing better than you think",
    "Your future self is cheering you on",
    "You're allowed to be proud of small wins",
    "Your story isn't over yet",
    "You make the world a little brighter",
    "Progress isn't always visible but it's happening",
    "You're exactly the right amount of you",
    "Your kindness ripples further than you know",
    "You're learning even when it doesn't feel like it",
    "Your existence matters",
    "You're braver than you believe",
    "Today you are enough",
    "You're writing your own adventure",
    "Your mistakes are just rough drafts",
    "You're allowed to rest and still be productive",
    "Your growth is happening at the perfect pace",
    "You're someone's reason to smile today",
    "You're more resilient than you realize",
    "Your ideas have value",
    "You're allowed to change your mind",
    "You're doing the best you can with what you have",
    "Your heart is in the right place",
    "You're exactly who you're supposed to be right now",
    "Your curiosity will take you places",
    "You're allowed to celebrate tiny victories",
    "Your perspective matters",
    "You're stronger for having tried",
    "Your authenticity is your superpower",
    "You're learning to trust yourself",
    "Your presence is a gift",
    "You're allowed to be human",
    "Your courage shows up in small ways too",
    "You're not behind, you're on your own timeline",
    "Your weirdness is wonderful",
    "You've survived every bad day so far",
    "Your gut instincts are usually right",
    "You're allowed to outgrow old versions of yourself",
    "Your sensitivity is a strength",
    "You're doing something right if you're here",
    "Your creativity sparks joy in others",
    "You're allowed to take up space",
    "Your boundaries are healthy and necessary",
    "You're more interesting than you think",
    "Your struggles are creating your strength",
    "You're allowed to be a work in progress",
    "Your laugh makes other people happy",
    "You're exactly weird enough",
    "Your questions are just as important as answers",
    "You're allowed to change directions",
    "Your energy affects rooms in the best way",
    "You're doing life at your own speed",
    "Your inner critic is not your friend",
    "You're allowed to be excited about small things",
    "Your thoughts don't define you",
    "You're more patient than you give yourself credit for",
    "Your dreams are valid no matter how strange",
    "You're allowed to not know everything",
    "Your past doesn't dictate your future",
    "You're exactly the right temperature today",
    "Your random acts of kindness count",
    "You're allowed to like what you like",
    "Your growth happens in invisible moments",
    "You're doing better than your anxiety says",
    "Your potential isn't expired",
    "You're allowed to feel proud",
    "Your intuition knows things your brain doesn't",
    "You're more loved than you realize",
  ];

  static const List<String> demotivationalMessages = [
    "I am probably a simulation",
    "I will never succeed", 
    "Anything could happen today and that scares me",
    "What if nothing I do matters?",
    "I'm just pretending to know what I'm doing",
    "Everyone else seems to have it figured out",
    "I'm falling behind and can't catch up",
    "What if I'm not as smart as I think I am?",
    "Nothing good ever lasts",
    "I'm just one person in billions",
    "My plants are probably judging my life choices",
    "What if my pets are disappointed in me?",
    "I still don't know what I want to be when I grow up and I'm an adult",
    "My browser history would horrify my ancestors",
    "I peaked in elementary school",
    "What if aliens are real but they're avoiding Earth because of me specifically?",
    "I have no idea how taxes work and I'm too afraid to ask",
    "My childhood imaginary friend probably moved on to someone cooler",
    "What if my GPS is just making stuff up?",
    "I still tie my shoes the wrong way",
    "My autocorrect knows me better than I know myself",
    "What if I'm the background character in someone else's story?",
    "I've been winging it since 2003",
    "My life's highlight reel is just me finding good parking spots",
    "What if the voices in my head are just really quiet?",
    "I'm one YouTube rabbit hole away from believing the earth is flat",
    "My carbon footprint is probably visible from space",
    "What if my dreams are more interesting than my waking life?",
    "I still count on my fingers and I'm not sorry",
    "My phone battery dies faster than my motivation",
    "What if I'm allergic to success?",
    "I put the 'pro' in procrastination",
    "My life needs a software update but I keep postponing it",
    "What if my horoscope is just making fun of me personally?",
    "I'm pretty sure my houseplants are plotting against me",
    "My biggest fear is that I left the stove on in 1987",
    "What if my memories are just really elaborate fanfiction?",
    "I'm still waiting for my Hogwarts letter and I'm 30",
    "My search history reads like a cry for help",
    "What if I'm the glitch in the matrix everyone's talking about?",
    "I am basically a houseplant with anxiety",
    "My WiFi password is stronger than my willpower",
    "I Google things I learned in school",
    "My backup plan needs a backup plan",
    "I adulted today and nobody died",
    "My therapist probably needs therapy after me",
    "I'm one minor inconvenience away from a breakdown",
    "My life coach would quit",
    "I peaked at age 7",
    "My houseplants have trust issues because of me",
    "I'm the human equivalent of a software bug",
    "My motivation left without a forwarding address",
    "I'm allergic to mornings",
    "My life runs on anxiety and caffeine",
    "I'm the reason they put warning labels on everything",
    "My GPS gave up on me",
    "I'm one notification away from losing it",
    "My attention span is sponsored by goldfish",
    "I collect regrets like Pokemon cards",
    "My inner child needs supervision",
    "I'm the plot twist nobody wanted",
    "My patience expired in 2019",
    "I'm running on fumes and false hope",
    "My brain's search function is broken",
    "I'm the human version of a loading screen",
    "My life's on airplane mode",
    "I'm one typo away from unemployment",
    "My willpower has left the chat",
    "I'm the reason Murphy invented his law",
    "My confidence is in airplane mode",
    "I'm buffering at 99%",
    "My adulting license should be revoked",
    "I'm the human equivalent of dial-up internet",
    "My motivation is out of office",
    "I'm one minor inconvenience from becoming feral",
  ];

  static Future<void> seedDatabase() async {
    await DatabaseService.clearMessages();
    
    for (String content in motivationalMessages) {
      await DatabaseService.insertMessage(
        Message(content: content, isMotivational: true),
      );
    }

    for (String content in demotivationalMessages) {
      await DatabaseService.insertMessage(
        Message(content: content, isMotivational: false),
      );
    }
  }
}
